#!/bin/bash


#https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script

upper_flag=false
numbers_flag=false
alphabet=ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ
#echo ${alphabet:2:1}

# Loop all parameters use $@
for i in "$@" ; do
    if [ "$i" == "-u" ]; then
        upper_flag=true;
    fi

#   use regex to check -n {{ value }}, this regex only accept numbers
    re='^[0-9]+$'
    if [[ "$i" =~ ${re} ]]; then
          numbers_arg=$i
    fi

#   the reason of using two checking are due to in some conditions -n is not in parameters list {$@}
    if [[ "$(echo "$0 $1" | grep -E -c '\-n')" -eq 1 ]] || [[ "$(echo "$@" | grep -E -c '\-n')" -eq 1 ]]; then
          numbers_flag=true;
    fi
done

  output="[${alphabet:${numbers_arg}:1}-ZA-${alphabet:${numbers_arg}-1:1}]"


if [ "$upper_flag" = true ] && [ "$numbers_flag" = true ]; then
  echo "${output}"
elif [ $numbers_flag = true ]; then
  echo "${output}" | tr "[:upper:]" "[:lower:]"
fi


