#!/bin/bash

file_name=$1

DICT="/usr/share/dict/words"

RESULT="result.txt"

CORRECT_WORKS="correct_words.txt"

COUNT_N=0

# execute decode then remove the line which start with Shift then save to result.txt
./decode "${file_name}" | sed '/^Shift/ d' | sed '/^$/ d'  > ${RESULT}


# read from result, and loop the elements
# change uppercase to lower case
# check is this word inside of dictionary or not, return check which is how many words gets
# if check greater than 1 which means current word is found in the dictionary, increase count_n and append this word into correct word.txt
while read -r line;do

  uppercase=$(echo "${line}" | tr "[:upper:]" "[:lower:]")

  check="$(grep -E -c "^${uppercase}$" ${DICT})"

  if [ "${check}" -ge 1 ]; then
      (( "COUNT_N+=1" )) || true
      echo "${line}" >> ${CORRECT_WORKS}
  fi

done < ${RESULT}

# format and process the output and display
# the display including how many number words are meaningful and display those words

echo "We have ${COUNT_N} words found, they are:"

if [ ${COUNT_N} -ge 1 ]; then

    while read -r line;do
      echo "${line}"
    done < ${CORRECT_WORKS}

fi

# clean up
rm -rf ${RESULT} ${CORRECT_WORKS}