#!/bin/bash

file_name=$1

alphabet=ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ


# loop in rang of 1-25
  for i in {1..25} ;
  do
    echo "Shift" "$i"

#    get input from << EOF or files line by line
    while input_content= read -r line;
    do

#      move by shifting changed --> ${alphabet:${i}:26}
        echo "$line" | tr "[a-z]" "[A-Z]" | tr "${alphabet:0:26}" "${alphabet:${i}:26}"
    done < "$file_name"

  done
