clean:
	rm Exe_*
thread:
	gcc 01_test_threads.c -pthread -o Exe_Thread
	./Exe_Thread
flipflop:
	gcc 02_flip_flop.c -pthread -o Exe_FlipFlop
	./Exe_FlipFlop
race:
	gcc 03_race_condition.c -pthread -o Exe_Race
	./Exe_Race
